### PR TITLE
Reaction Based Role system

### LINKED ISSUE #62: Reactions for roles
image

### PR DESCRIPTION
**Pull request by Pierre-Demessence**
Fetched the code from @SimplyJpk's PR and re-created the PR since his repo has been deleted.

Closes #62

### CODE REVIEW

**Comment by SimplyJpk** [comment]
#106 now groups role updates together, helping to prevent potential throttling issues. @Pierre-Demessence

**Comment by SimplyJpk** [comment]
Not that I expect it to happen any time soon, but don't merge. 
How I get the user after delay can sometimes fail.

**Comment by SimplyJpk** [comment]
#118 adds onto this, should fix some of the current problems, I'll do more testing sometime soon.

(Thought my PR would continue here, guess not.)

**Comment by Pierre-Demessence** [comment]
Closing as the branch has been polluted

**Pull request closed without merging**
