### PR TITLE
Added 'hastebin' command, general cleanup.

### LINKED ISSUE #64: !hastebin command
A `!hastebin <code>` command that will publish the code to hastebin and then put the link in the chat.

### PR DESCRIPTION
**Pull request by djgaven588**
Addresses the '!hastebin command' issue [https://github.com/Sirush/UDHBot/issues/64](url)
Cleaned up some code, mainly making things more consistent throughout the code.
Removed some warnings that appear in Visual Studio regarding async methods not being awaited for, even though they were meant to not be awaited for.

### CODE REVIEW

**Comment by djgaven588** [comment]
New changes:
Replaced all usage of Console.Log with Debug.Log, which formats everything properly. This generally improves being able to quickly find the source of something.

**Comment by djgaven588** [comment]
New changes:
Hastebin command is now tested and works as expected.
Commented compile command to make it easier to understand.
Updated the following limits:
- Hastebin upload limit for "hastebin" and "compile" commands: 10,000 -> 20,000, some outputs are a bit longer and them being cut off is a bit annoying for some.
- Message length for "compile" when responding to user: 1988 -> 1250, I found it was easy to abuse the compile command to flood chat making this change just for preventing really long messages.
- Messange length for "hastebin" when responding to user: 500 -> 450, reduced slightly as the code preview doesn't need to be that long.

**Comment by djgaven588** [comment]
I have tested everything I have changed, and see no issues. This should be ready to be merged after it is reviewed.

**Comment by Pierre-Demessence** [comment]
I fixed the merge conflicts, but given this PR is old it might require thorough testing.

**Comment by djgaven588** [comment]
Honestly didn't think after a year this would be considered for merging XD

**Pull request closed without merging**
